// Package pricing values observed token usage in micro-USD (millionths of a
// dollar) using an offline-first ladder of price tables.
//
// The ladder, most authoritative first:
//
//  1. config overrides — the user's own rates, always win. A PARTIAL override
//     (say output only) replaces just the rates it names: the rest come from
//     the rung below, because "override this rate" is not "delete the others";
//  2. the runtime-refreshed LiteLLM table cached in the data dir;
//  3. the runtime-refreshed, provider-scoped Models.dev table;
//  4. the embedded LiteLLM and Models.dev snapshots for offline use;
//  5. nothing. A model no rung can price stays unpriced. Zero requires an
//     explicitly verified free service.
//
// VENDOR COST vs ESTIMATE: Some adapters emit cost already stamped by the
// provider (copilot's nano-aiu, crush's session cost, pi/openclaw via the
// vendor, goose's provider-reported figure). This cost, stamped by the adapter,
// is the source of truth and is never overwritten by the price ladder — the
// ladder is a public-rate-card estimate of the same charge, and letting the
// estimate win is a strict loss of fidelity. Adapters that do not emit cost
// rely on pricing.Pricer to consult the ladder at collect time. An event left
// unpriced (Pricer returns ok=false or is nil) is stored with nil
// CostMicroUSD — the honest state, since a stored 0 would claim the request
// was free.
//
// LONG-CONTEXT TIERS are whole-request rate cards selected by prompt size, not
// marginal breakpoints. Every provider measures the boundary on input tokens
// (cached or not) and switches cards for the FULL request — OpenAI over 272K
// input, Google over 200K, etc. Charged at Rates.Long if the request's
// ContextTokens exceed the model's threshold, never marginal. The Charge type
// unifies per-request and aggregated pricing, and Aggregate marks the latter so
// a thousand short turns can never add up to one long-context request.
//
// EMBEDDED SNAPSHOT: the go:embed'ed filtered LiteLLM table is regenerated by
// internal/pricing/gensnapshot.go and is guaranteed to provide a baseline price
// for any model that appears in published documentation. It keeps a firewalled
// install pricing while offline. Partial config overrides can reach tables below
// the topmost rung (overrides fill missing fields from the rung they displace),
// and the snapshot is the floor: a model it cannot price remains unpriced.
//
// Integer micro-USD is the unit everywhere: it sums exactly across millions of
// rows, where float dollars drift. The package imports only model.
package pricing

import (
	"math"
	"strings"

	"github.com/RandomCodeSpace/aiusage-core/model"
)

// SourceOverride is the price_source stamped when a config override priced the
// event. The other two rungs stamp "litellm-<fetch date>" and
// "embedded-<snapshot date>", built by the table loaders.
const SourceOverride = "override"

// longContextStamp is appended to the price_source of an event that crossed its
// model's long-context threshold, so a row billed off the second rate card says
// so ("litellm-2026-08-16+long-context"). It is a suffix on the existing open
// vocabulary, not a new column: nothing parses price_source, and the alternative
// — a row priced at double the base rate with a stamp naming only the table —
// is precisely the silent failure this change exists to end.
const longContextStamp = "+long-context"

// Rates are the per-token USD rates for one model, in LiteLLM's units (dollars
// per single token). A zero field means "not published", not "free"; Cost
// resolves each zero to the documented fallback rate.
type Rates struct {
	// Free distinguishes a verified free service from an unpublished zero rate.
	Free         bool
	Input        float64
	Output       float64
	CacheRead    float64 // 0 -> the input rate: a cache read is a discounted input token
	CacheWrite5m float64 // 0 -> the input rate: writing a 5m entry costs at least the input
	CacheWrite1h float64 // 0 -> the resolved 5m write rate
	InputBatch   float64 // 0 -> the standard input rate (no batch tier published)
	OutputBatch  float64 // 0 -> the standard output rate

	// Long is the second rate card, used for a request whose prompt crosses
	// this model's published threshold. Zero Threshold means the model has no
	// long-context tier, which is the common case.
	Long LongContext
}

// LongContext is a model's above-threshold rate card. Providers switch cards for
// the WHOLE request rather than billing a band of tokens separately — OpenAI:
// "Prompts with >272K input tokens are priced at 2x input and 1.5x output for
// the full request"; Google: "If a query input context is longer than 200K
// tokens, all tokens (input and output) are charged at long context rates" — so
// this is a rate card selected per request, never a marginal breakpoint. Reading
// LiteLLM's "_above_200k_tokens" field naming as marginal is an artifact of the
// name and matches no documented provider behaviour; it also under-bills by a
// factor of ten on real traffic, because a crossing request is typically broad
// (a large cache read plus a modest input) rather than one bucket deep past the
// line.
//
// Threshold is per model and comes from the LiteLLM field name (see
// longContextCard): the live table publishes five distinct boundaries — 128K,
// 200K, 256K, 272K and 512K — so a hardcoded 200K would be wrong for four of
// them. A zero rate here falls back to the same-named base rate, except an
// absent 1h write rate uses the resolved long-context 5m write rate:
// LiteLLM publishes an above-threshold rate only for the buckets it prices, and
// inventing a multiple of the base rate for the rest would be a made-up number.
type LongContext struct {
	// Threshold is the prompt size, in tokens, above which this card applies.
	// 0 means the model publishes no long-context tier.
	Threshold int64

	Input        float64
	Output       float64
	CacheRead    float64
	CacheWrite5m float64
	CacheWrite1h float64
}

// Priceable reports whether the rates carry a price or a verified free status.
// An ordinary all-zero entry remains unknown.
func (r Rates) Priceable() bool { return r.Free || r.Input > 0 || r.Output > 0 }

// fill returns r with every unset (zero) rate taken from base. It is how a
// PARTIAL config override composes with the rung it displaces: a user who sets
// only the output rate means "bill output at mine, the rest as published", so
// the fields they left out keep the table's rates instead of valuing those
// tokens at nothing.
func (r Rates) fill(base Rates) Rates {
	named := r // the rates the caller actually set, before any filling
	if r.Input == 0 {
		r.Input = base.Input
	}
	if r.Output == 0 {
		r.Output = base.Output
	}
	if r.CacheRead == 0 {
		r.CacheRead = base.CacheRead
	}
	if r.CacheWrite5m == 0 {
		r.CacheWrite5m = base.CacheWrite5m
	}
	if r.CacheWrite1h == 0 {
		r.CacheWrite1h = base.CacheWrite1h
	}
	if r.InputBatch == 0 {
		r.InputBatch = base.InputBatch
	}
	if r.OutputBatch == 0 {
		r.OutputBatch = base.OutputBatch
	}
	if r.Long.Threshold == 0 {
		// The long-context card is inherited whole, never blended across
		// sources: a card assumes its own boundary, so taking the threshold
		// from one table and a rate from another would price both tiers wrong.
		// A config override cannot express a tier at all, so this is how an
		// overridden model keeps the published card of the rung it displaced —
		// "override this rate" is not "delete the long-context tier".
		//
		// A rate the override DID name is then dropped from the inherited card,
		// which leaves Cost's "0 means not published" fallback to bill that
		// bucket at the user's rate on both cards. The top rung must win for
		// what it names, above the threshold as well as below it; the buckets it
		// says nothing about keep the published pair.
		long := base.Long
		if named.Input != 0 {
			long.Input = 0
		}
		if named.Output != 0 {
			long.Output = 0
		}
		if named.CacheRead != 0 {
			long.CacheRead = 0
		}
		if named.CacheWrite5m != 0 {
			long.CacheWrite5m = 0
		}
		if named.CacheWrite1h != 0 {
			long.CacheWrite1h = 0
		}
		r.Long = long
	}
	return r
}

// Charge is the token shape being priced: the counts, plus the three facts that
// change which rate applies (the model/provider identity, the service tier, and
// whether reasoning tokens are billed on top of output or already inside it).
type Charge struct {
	Model       string
	Provider    string
	ServiceTier string

	Input     int64
	Output    int64
	Reasoning int64
	CacheRead int64
	// CacheWrite5m / CacheWrite1h split the cache-creation tokens by the
	// requested entry lifetime. A source that reports no split puts everything
	// in CacheWrite5m, which is the documented fallback (the 1h write is the
	// dearer of the two, so this never over-bills).
	CacheWrite5m int64
	CacheWrite1h int64

	// AdditiveReasoning bills Reasoning at the output rate on top of Output.
	// False means reasoning is already contained in Output (see
	// model.ReasoningModeFor) and billing it again would double charge.
	AdditiveReasoning bool

	// Aggregate marks a charge that stands for SEVERAL requests summed together
	// — report's display-time valuation of unpriced groups, which arrives
	// pre-aggregated per model — rather than describing one. Its token counts
	// are a total, not a prompt size, so no long-context tier is selected for
	// it: a thousand short turns must never add up to one long-context request.
	// The zero value is therefore "one request", which is what every ledger path
	// prices.
	Aggregate bool
}

// Tokens is the total token count being charged, used to tell "no usage, so
// genuinely zero" apart from "priced at zero", which is never reported.
func (c Charge) Tokens() int64 {
	return c.Input + c.Output + c.CacheRead + c.CacheWrite5m + c.CacheWrite1h + c.Reasoning
}

// ContextTokens is the prompt size the long-context tier is measured against:
// every bucket that is part of the request's input, CACHED OR NOT. Output is
// excluded because every provider measures the boundary on the prompt (OpenAI:
// ">272K input tokens"; Google: "query input context longer than 200K tokens").
//
// Cache reads are the load-bearing term. The adapters normalize a provider's
// prompt into disjoint buckets — codex stores `input = raw_input - cached`
// because the Responses API reports cached_tokens as a SUBSET of input_tokens —
// so Input + CacheRead is exactly the number OpenAI's own sentence is about, and
// counting Input alone would be reading a normalization artifact as a prompt
// size. Measured on this machine's ledger: 17 rows cross 272K on uncached input,
// 551 cross on input + cache read. Cache writes join them for the same reason —
// Anthropic's context-window doc counts input_tokens, cache_read_input_tokens
// and cache_creation_input_tokens alike toward the window, and on this ledger
// they add no crossings on top.
func (c Charge) ContextTokens() int64 {
	return c.Input + c.CacheRead + c.CacheWrite5m + c.CacheWrite1h
}

// ChargeFor derives the Charge for a stored usage event: token counts straight
// off the event, the reasoning-billing rule from the event's tool, and the
// cache-write split from the transient CacheTTL enrichment. A split that does
// not add up to the recorded cache-creation count is discarded in favour of
// "all 5m" — a partial split would silently drop billable tokens.
func ChargeFor(e model.UsageEvent) Charge {
	w5, w1 := e.CacheTTL.Ephemeral5m, e.CacheTTL.Ephemeral1h
	if w5 < 0 || w1 < 0 || w5+w1 != e.CacheCreationTokens {
		w5, w1 = e.CacheCreationTokens, 0
	}
	return Charge{
		Model:             e.Model,
		Provider:          e.Provider,
		ServiceTier:       e.ServiceTier,
		Input:             e.InputTokens,
		Output:            e.OutputTokens,
		Reasoning:         e.ReasoningTokens,
		CacheRead:         e.CacheReadTokens,
		CacheWrite5m:      w5,
		CacheWrite1h:      w1,
		AdditiveReasoning: model.ReasoningModeFor(e.Tool) == model.ReasoningAdditive,
	}
}

// longApplies reports whether this charge is billed off the long-context card:
// the model publishes one, the charge is a single request, and its prompt is
// STRICTLY larger than the threshold. Strict is what the providers state —
// OpenAI "Prompts with >272K input tokens", Google "longer than 200K tokens" —
// and it is the reading that never bills a request that fits inside the short
// card at the long rate. (Vertex's Sonnet 4.5 footnote is the one ">=" in the
// wild; LiteLLM publishes no comparator, so one rule serves the table and this
// is the one the affected models document.)
func (r Rates) longApplies(c Charge) bool {
	return r.Long.Threshold > 0 && !c.Aggregate && c.ContextTokens() > r.Long.Threshold
}

// Cost values a charge at these rates, in micro-USD, rounding half up. The
// result is never negative and saturates at math.MaxInt64 micro-USD.
//
// A request over the model's long-context threshold is billed ENTIRELY off the
// second rate card — every bucket, not the excess above the line.
func (r Rates) Cost(c Charge) int64 {
	if r.Free {
		return 0
	}
	in, out := r.Input, r.Output
	cacheRead, write5m, write1h := r.CacheRead, r.CacheWrite5m, r.CacheWrite1h
	if r.longApplies(c) {
		write1h = r.Long.CacheWrite1h
		if r.Long.Input > 0 {
			in = r.Long.Input
		}
		if r.Long.Output > 0 {
			out = r.Long.Output
		}
		if r.Long.CacheRead > 0 {
			cacheRead = r.Long.CacheRead
		}
		if r.Long.CacheWrite5m > 0 {
			write5m = r.Long.CacheWrite5m
		}
	}
	// The batch tier is applied AFTER the card is chosen and still wins, because
	// LiteLLM publishes no "*_batches_above_<N>k_tokens" rate for any model
	// (verified against the 3,020-model table): a published batch rate for the
	// wrong card beats a rate this package would have to invent. A long-context
	// batch request is therefore under-billed; no row in this ledger is one.
	if isBatchTier(c.ServiceTier) {
		if r.InputBatch > 0 {
			in = r.InputBatch
		}
		if r.OutputBatch > 0 {
			out = r.OutputBatch
		}
	}
	if cacheRead == 0 {
		cacheRead = in
	}
	if write5m == 0 {
		write5m = in
	}
	if write1h == 0 {
		write1h = write5m
	}

	usd := float64(c.Input)*in +
		float64(c.Output)*out +
		float64(c.CacheRead)*cacheRead +
		float64(c.CacheWrite5m)*write5m +
		float64(c.CacheWrite1h)*write1h
	if c.AdditiveReasoning {
		usd += float64(c.Reasoning) * out
	}
	return microUSD(usd)
}

// isBatchTier reports whether a provider service tier is a batch tier, which
// LiteLLM prices in its *_batches fields (roughly half the standard rate).
func isBatchTier(tier string) bool {
	return strings.Contains(strings.ToLower(tier), "batch")
}

// microUSD converts dollars to millionths, rounding half up. Charges are never
// negative, so "half up" and "half away from zero" coincide.
func microUSD(usd float64) int64 {
	if usd <= 0 {
		return 0
	}
	micro := math.Floor(usd*1e6 + 0.5)
	if micro >= float64(math.MaxInt64) {
		return math.MaxInt64
	}
	return int64(micro)
}

// Table is one rung of the ladder: a model->rates map plus the price_source
// string to stamp when it prices something.
type Table struct {
	Source string
	Models map[string]Rates
	// ProviderScoped tables require the recorded provider as well as the model.
	ProviderScoped bool
}

// Lookup resolves rates for a (provider, model) pair, trying the provider's
// namespaced LiteLLM key before the bare model id so a proxied model is priced
// at the proxy's rates when the table publishes them. A table row with no
// usable price counts as a miss so the next rung gets a chance.
func (t *Table) Lookup(provider, name string) (Rates, bool) {
	if t == nil || len(t.Models) == 0 {
		return Rates{}, false
	}
	if t.ProviderScoped {
		if provider == model.ProviderGitHub {
			provider = "github-copilot"
		}
		if provider == "" {
			return Rates{}, false
		}
		name = strings.TrimSpace(name)
		name = strings.TrimPrefix(name, provider+"/")
		r, ok := t.Models[provider+"/"+name]
		return r, ok && r.Priceable()
	}
	for _, key := range lookupKeys(provider, name) {
		if r, ok := t.Models[key]; ok && r.Priceable() {
			return r, true
		}
	}
	return Rates{}, false
}

// lookupKeys lists the table keys to try for a (provider, model) pair, most
// specific first: the provider-namespaced forms, the model id as stored, its
// lowercase form, and finally the id with any leading "vendor/" segment
// stripped (opencode and openrouter-style ids arrive pre-namespaced).
func lookupKeys(provider, name string) []string {
	n := strings.TrimSpace(name)
	if n == "" {
		return nil
	}
	keys := make([]string, 0, 6)
	for _, p := range providerPrefixes(provider) {
		keys = append(keys, p+n)
	}
	keys = append(keys, n)
	if l := strings.ToLower(n); l != n {
		keys = append(keys, l)
	}
	if i := strings.IndexByte(n, '/'); i >= 0 && i+1 < len(n) {
		keys = append(keys, n[i+1:])
	}
	return keys
}

// providerPrefixes maps a billing provider to the LiteLLM key namespaces that
// carry its rates. LiteLLM keys Anthropic and OpenAI models bare as well, which
// the caller covers with the un-prefixed candidate.
func providerPrefixes(provider string) []string {
	switch provider {
	case model.ProviderGoogle:
		return []string{"gemini/", "vertex_ai/"}
	case model.ProviderGitHub:
		return []string{"github_copilot/"}
	case model.ProviderOpenAI:
		return []string{"openai/"}
	case model.ProviderAnthropic:
		return []string{"anthropic/"}
	case "":
		return nil
	default:
		// Data-driven providers (opencode's providerID, hermes'
		// billing_provider) already match LiteLLM's namespace convention for
		// the vendors they name.
		return []string{provider + "/"}
	}
}

// Price resolves a charge against the ladder and returns the cost in micro-USD
// plus the price_source that produced it. ok=false means unpriced: NO rung
// could value this charge shape. A rung that knows the model but publishes no
// rate for the tokens being charged (an output-only row against an input-only
// charge) is a gap in that table, not a free request, and gets the same
// recovery an unpriceable row gets — the next rung down is tried. Only when the
// ladder runs out is the charge reported unpriced, never $0.00.
//
// A charge billed off the model's long-context card carries longContextStamp on
// the end of whatever the rung stamped.
func (e *Engine) Price(c Charge) (int64, string, bool) {
	if e == nil {
		return 0, "", false
	}
	tables := e.tables()
	for i, t := range tables {
		r, ok := t.Lookup(c.Provider, c.Model)
		if !ok {
			continue
		}
		source := t.Source
		if t == e.overrides {
			r, source = mergeOverride(r, source, tables[i+1:], c)
		}
		if r.Free {
			return 0, source + "+free", true
		}
		micro := r.Cost(c)
		if micro == 0 && c.Tokens() > 0 {
			continue // this rung prices nothing this charge is made of
		}
		if r.longApplies(c) {
			source += longContextStamp
		}
		return micro, source, true
	}
	return 0, "", false
}

// mergeOverride completes a config override from the first lower rung that
// knows the same model — the rung the override displaced. Replacing that rung's
// whole row with a partial override is what used to leave input, cache and
// batch tokens valued at zero for a model whose output rate was the only one
// the user wanted changed.
//
// The stamp names both tables ("override+litellm-<date>") whenever the lower
// rung actually moved THIS charge's price, so price_source never credits the
// override with a number it did not produce on its own; a charge the override
// prices unaided still stamps a plain "override".
func mergeOverride(r Rates, source string, lower []*Table, c Charge) (Rates, string) {
	for _, t := range lower {
		base, ok := t.Lookup(c.Provider, c.Model)
		if !ok {
			continue
		}
		merged := r.fill(base)
		if merged.Cost(c) == r.Cost(c) {
			return r, source
		}
		return merged, source + "+" + t.Source
	}
	return r, source
}

// PriceEvent prices a usage event. It is the collector-facing entry point and
// satisfies collect.Pricer.
func (e *Engine) PriceEvent(ev model.UsageEvent) (int64, string, bool) {
	return e.Price(ChargeFor(ev))
}
